services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: grainzon
      POSTGRES_USER: grainzon
      POSTGRES_PASSWORD: grainzon
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
